### ISSUE TITLE
List done / undone event

### ISSUE THREAD

**Issue by edmundmok** [CS2103AUG2016-W13-C4/main#100]
Right now the list done/undone event only toggles the boolean in model.

Is it possible to have an event to call in CommandBox2(the buttons area) that does the switching? 
instead of writing this:

``` java
    @FXML
    private void switchToListDoneView() {
        logic.execute("list done");
    }

    @FXML
    private void switchToListUndoneView() {
        logic.execute("list");
    }
```

This is quite lame. But I have no other way of switching unless I add another a model dependency in UI.

**Comment by linhany** [comment]
Yeah but need to have the mouse click to toggle them as well, so you want to raise an event with the mouse click too?

**Comment by linhany** [comment]
Not sure if the event posting should be done in List command class, or model manager class. Any ideas

**Comment by edmundmok** [comment]
Just want an event to call when the button is clicked that switches the view

**Comment by linhany** [comment]
Not sure what you mean by calling an event. You want to post an event that switches the view?

**Comment by linhany** [comment]
Even if you post the event you still have to set the boolean variable in model

**Comment by linhany** [comment]
Btw the list done/undone event doesn't only toggle the boolean in model, the event actually causes the change in view. So that's what you are looking for?

**Comment by linhany** [comment]
Can u elaborate why it is quite lame, seems to be the right way to do this. Executing list or list done will call the command, which posts the event and updates the boolean variable. So instead of that, you want another event, an event to update boolean variable + post event? So an event that posts another event?

**Comment by edmundmok** [comment]
Oh ya. I think i misread it.
But still need to update the boolean and updatefilteredlist manually.

I'm not sure if executing a command from the UI is the best way to implement the functionality of these buttons thats why.

**Comment by edmundmok** [comment]
What I meant was an event that does all those stuff for me. So probably the list done also calls this event and model subscribes to it to update the boolean + updatefilteredlist.

Then instead of executing a command in the UI, I just call that same event the list done calls.

**Comment by linhany** [comment]
Alright I get what you mean. This is straightforward to change, but after giving it more thought,

1) I don't see why executing command in UI is wrong. If you just call an event, there would be no feedback in tooltip that you have switched to list done view. On the other hand, if you execute a command, it feels more natural to the user and he can see that he has switched views from the command result feedback. (why doesn't this feedback occur currently?)

2) I don't like the idea of having a button to switch views in the first place.  As a user, all the other commands are only accessible by typing. Suddenly you have a command that works with typing/mouse click. Are the buttons really necessary? I think the point of that is to let user know which view they are in right? I'm sure there are better ways to do that. For example, the sentence "Currently listing all done tasks" can be kept at the top of tooltip when in list done view. Or can add different colour to the done task cards background. Etc..

@CS2103AUG2016-W13-C4/developers 
I'm just one person in the group so this is ultimately a group decision

**Comment by edmundmok** [comment]
The point is not the button actually. The primary function is to indicate which view the user is currently on. So it responds to list and list undone. I just used a button because its the easiest to set up a 'selected' style.  And I thought since its a button might as well support clickability.

I'm fine with leaving it as executing command, just not sure if its the right way to do it.

**Comment by edmundmok** [comment]
Updated it to feedback the change in list on the result display

**Comment by Zhiyuan-Amos** [comment]
For this I don't have much opinion since I'm not familiar with how the UI works :( Prob can discuss in class ba ^^
