### ISSUE TITLE
Type any command to get a tooltip on the command format!

### ISSUE THREAD

**Issue by linhany** [CS2103AUG2016-W13-C4/main#103]
I get this message output sometimes when I clear the task manager, instead of the output "Task manager data cleared"

**Comment by edmundmok** [comment]
Thats caused by me. But i'm getting the correct output

**Comment by linhany** [comment]
You have to try a few times. Sometimes correct, sometimes wrong output

**Comment by edmundmok** [comment]
Lol. If i type fast it will occur.
