### ISSUE TITLE
Tests and refactor

### ISSUE THREAD

**Issue by edmundmok** [CS2103AUG2016-W13-C4/main#40]
Add custom tests and refactor for code you have written for everything you have written and are going to write.
Add assertions/exceptions/defensiving coding/logging for your code also.
# SPAM ASSERT WHEREVER POSSIBLE. SAME FOR THE REST.

**Comment by edmundmok** [comment]
Create your own version of this issue.

**Comment by Zhiyuan-Amos** [comment]
@CS2103AUG2016-W13-C4/developers I just close this ah haha
