### ISSUE TITLE
update User Guide "Adding a task with deadline"

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [CS2103AUG2016-W13-C4/main#57]
Acceptable date-time formats:
1. DATE - "3 days later"
2. DATE - "next sat"

Not acceptable date-time formats:
1. Formal Dates not allowed, otherwise error will occur! i.e 28/12/2016 not allowed!
2. Time must be demarcated with a colon i.e 10:30am, not 1030am

// Extra notes:
"13th Sep 2015"
Year must be specified completely e.g 2015, not 15

**Comment by Zhiyuan-Amos** [comment]
@CS2103AUG2016-W13-C4/developers hey guys need your thoughts on this. Natty allows parsing for "acceptable date-time formats", but not those under "not acceptable date-time formats". You guys ok with it (I mean there's no other way la cuz Natty doesn't support it).

**Comment by edmundmok** [comment]
I think SimpleDateFormat supports it.
Try this? 
`SimpleDateFormat sdfParser = new SimpleDateFormat("d-MM-yyyy")`
or
`SimpleDateFormat sdfParser = new SimpleDateFormat("dd-MM-yyyy")`

**Comment by Zhiyuan-Amos** [comment]
ps for formal dates, Natty supports but it must be in the following formats:

1978-01-28
1984/04/02
1/02/1980 (m/dd/yyyy)
2/28/79

Formats that don't work:
01021980
010280

So shall we support?

**Comment by edmundmok** [comment]
last 2 can leave out lol. the ones that natty does support can be useful. and since its already built in anway.

user guide must be clear that month comes first i guess. no way to make day first?

**Comment by Zhiyuan-Amos** [comment]
Nope, no way to do so. Thanks, will update user guide accordingly
