### ISSUE TITLE
Design decision for error messages given we have tooltip

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [CS2103AUG2016-W13-C4/main#67]

**Comment by Zhiyuan-Amos** [comment]
Error message for AddCommand is similar to the tooltip.

**Comment by fisherhx** [comment]
If possible provide them with which aspect is causing the error?

**Comment by edmundmok** [comment]
When does add command produce an error message? Only for invalid priorities?

**Comment by Zhiyuan-Amos** [comment]
invalid priorities doesn't give error message. as previously discussed, all invalid priorities will be set as medium priority. 

AddCommand only produces error message when
1. argsTrimmed.isEmpty() i.e "add               "
2. For some reason the regex doesn't match (mainly for recurrence rate matcher. if user keys in "repeat every days 3")
3. if (rateString != null && timePeriodString == null) e.g "repeat every 3"
4. if(recurrenceRate != null && startDate == null && endDate == null) i.e if user specifies repeat every 3 days, without giving start date or end date.

Number 4. is a design decision we can change though, like for e.g maybe "eat bingsu repeat every 3 days", we can just assign startDate to be today.
