### ISSUE TITLE
Clashing events

### ISSUE THREAD

**Issue by edmundmok** [CS2103AUG2016-W13-C4/main#69]
Are we still implementing warning messages for clashing events?

**Comment by Zhiyuan-Amos** [comment]
Should be ok.

**Comment by edmundmok** [comment]
Lol ok means yes or no?

**Comment by Zhiyuan-Amos** [comment]
falls under 1 star (i.e good to have feature lor haha). Wait for the rest to respond?

**Comment by linhany** [comment]
Imo a little warning is good. But not high priority. Can move to 0.4/0.5
