### ISSUE TITLE
Issues with Parser

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [CS2103AUG2016-W13-C4/main#70]
Hey guys, I think there's a major design issue with Parser.

The reason we decided to use a comma to seperate between the name and the rest of the fields, is because it's a simple and convenient way to do so. E.g "eat bingsu, by 10:30pm" is easy to parse.

However, the issue lies in these examples: "eat bingsu, by somerset 313", which will parse it as 3pm or something like that. My main point is, test cases like this will negate our intended effect of putting a comma after the name. **As such, it doesn't matter anymore whether we put the comma or not because of test cases like this.**

As such, shall we revert the Parser back to not having commas at all? This will actually be easier to parse in my opinion. 

Not sure whether can finish by Milestone 3 or not though.

**Comment by edmundmok** [comment]
Leaving the decision to you if you think commas are necessary or not. For me, doesn't matter. I thought it would make parsing easier but turns out it complicates things. So if you remove comma is it easier to parse? Or still have a problem filtering out the name portion.

**Comment by Zhiyuan-Amos** [comment]
@fisherhx your thoughts on this? 

Further issues, consider the 2 test cases:
"eat bingsu, start 6am end 7am"
"eat bingsu, end 7am".

The regex detects ", start" and "end", but it doesn't detect **", end"** (note the comma space), so the comma will result in me having to generate another regex to spot the keyword end with the comma, and without the comma.

**Comment by fisherhx** [comment]
I am already doing the second one for the edit parsing so if you wanna remove the comma then I am fine with it.

**Comment by linhany** [comment]
@Zhiyuan-Amos One way would be: leave out the comma, let user wrap problematic task names in `''`, e.g. `'eat bingsu by somerset 313'`. Our live preview will alert user as to whether their input will be interpreted wrongly, so they can correct it immediately by putting their task name in quotations. If user wants to include `''` as part of their task name, tell them that we reserve this symbol, and ask them to use `""` instead.
