### ISSUE TITLE
Todo List is getting cluttered easily with my task card

### ISSUE THREAD

**Issue by edmundmok** [CS2103AUG2016-W13-C4/main#71]
Suggestion: allow the user to use keyboard to move up and down the list (instead of having to scroll with mouse) THINK VIM CONTROLS.

**Comment by linhany** [comment]
`down` and `up` commands? `SHIFT` + `down key on keyboard?` Reduce the size of the task cards? Use `find` to scroll to the section you want to look at? Use `overdue` `today` `timed` `untimed` command words to scroll to the appropriate section? Use these words separately or as part of `find`? (Assuming we are splitting the tasks into different sections like in our UI in user guide.) E.g. `find untimed`, or use `untimed`. How to deal with task names that have these words? My suggestion would be to use `''`, as a tool for user to let us know that something is a task name and not a keyword, like what i mentioned in the parsing problem issue

**Comment by edmundmok** [comment]
modifer + arrowkey seems to be the best. moves the 'selector' appropriately.
