### ISSUE TITLE
Convert Task parameters (startDate, endDate, recurrenceRate) to Optional?

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [CS2103AUG2016-W13-C4/main#86]
one star- this is optional as well LOL

**Comment by Zhiyuan-Amos** [comment]
Hi guys, for purpose of code quality, should we change the parameters of `Task`class to Optional instead? So that the code looks tidier in my opinion.

**Comment by edmundmok** [comment]
I think that time linhan attempted this but there was some post online that you should avoid using optionals for the class attributes (but should use for getter methods). So we changed back to just normal instead of optional
