### ISSUE TITLE
Possible improvement to invalid command action

### ISSUE THREAD

**Issue by linhany** [CS2103AUG2016-W13-C4/main#94]
Right now it is quite annoying if invalid command is typed, the typing position is moved to the front, hard to edit the command, need to press --> all the way (assuming no mouse). Improvements: an invalid command clears the text box or keeps typing position at the end.

**Comment by Zhiyuan-Amos** [comment]
@ylhlh currently on my side invalid command clears text box leh

**Comment by linhany** [comment]
@Zhiyuan-Amos bunny changed it alr i think
