### ISSUE TITLE
Done + Changed the model manager

### ISSUE THREAD

**Issue by edmundmok** [CS2103AUG2016-W13-C4/main#98]
done on a recurring task only updates the start, end not changed.

Also, I changed the modelmanager methods resetData and deleteTask to what they were initially - to reset/delete from the undone list. Split into two methods instead of having a state dependent behavior cause my redo needs these methods (might cause different behavior than what was 'saved' before because redo calls execute, which depends on the viewing state if I left the methods as they were)

so the delete command now has 2 delete helper methods not sure if should combine. just wanted to make it pass the test first

**Comment by linhany** [comment]
done on a recurring task only updates the start, end not changed.

@Zhiyuan-Amos Your updateRecurringTask method problem I think. Want me to fix for u?

**Comment by linhany** [comment]
I just changed the else if to if. Should be fixed

**Comment by Zhiyuan-Amos** [comment]
@ylhlh just take my code. mark yourself as the author ba
